# Generated by Django 5.2 on 2025-05-05 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('lugar', models.CharField(choices=[('Sede Norte', 'Sede Norte'), ('Sede Centro', 'Sede Centro'), ('Sede Sur', 'Sede Sur')], max_length=100)),
                ('especialista', models.CharField(choices=[('Dr. Gómez', 'Dr. Gómez'), ('Dra. Ramírez', 'Dra. Ramírez'), ('Dr. Torres', 'Dr. Torres')], max_length=100)),
                ('area', models.CharField(choices=[('Cardiología', 'Cardiología'), ('Neurología', 'Neurología'), ('Dermatología', 'Dermatología')], max_length=100)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
