# Generated by Django 5.2 on 2025-05-06 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
